// Generated by CoffeeScript 1.4.0

module.exports = function(models) {
  var User;
  User = models.User;
  return {
    index: function(req, res) {
      if (!req.user) {
        req.flash('error', 'not authorized');
        res.redirect('/login');
        return;
      }
      return User.findExceptMyself(req.user.id, function(err, users) {
        return res.render("index", {
          title: "Simplest Chat",
          users: users
        });
      });
    },
    login: function(req, res) {
      if (req.user) {
        res.redirect('/');
      }
      return res.render("login", {
        title: "Simplest Chat!",
        errors: req.flash('error')
      });
    },
    logout: function(req, res) {
      req.logout();
      return res.redirect('login');
    }
  };
};
