// Generated by CoffeeScript 1.4.0
var Schema, UserSchema, db, mongoose;

mongoose = require('mongoose');

db = mongoose.connect('mongodb://localhost/simplest-chat');

Schema = db.Schema;

UserSchema = new Schema({
  name: String,
  password: String,
  connected: {
    type: Boolean,
    "default": false
  }
});

UserSchema.methods.validatePassword = function(password) {
  return this.password === password;
};

UserSchema.methods.is_signed_in = function() {
  return this.signed_in;
};

UserSchema.statics.findExceptMyself = function(my_id, cb) {
  return this.where('_id').ne(my_id).exec(cb);
};

module.exports.User = mongoose.model('User', UserSchema);
