// Generated by CoffeeScript 1.4.0
var Schema, UserSchema, db, mongoose;

mongoose = require('mongoose');

db = mongoose.connect('mongodb://localhost/simplest-chat');

Schema = db.Schema;

UserSchema = new Schema({
  name: String,
  password: String
});

UserSchema.methods.validatePassword = function(password) {
  return this.password === password;
};

module.exports.User = mongoose.model('User', UserSchema);
